spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/reminder_db}
    username: ${DB_USERNAME:reminder_user}
    password: ${DB_PASSWORD:reminder_pass}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

  mail:
    host: ${MAIL_HOST:live.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:api}
    password: ${MAIL_PASSWORD:03fc5cd903ba122bfd00f1ca5db295e9}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    mail.smtp.ssl.trust: live.smtp.mailtrap.io

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:default_test_token}
    username: ${TELEGRAM_BOT_NAME:remindersSenderApp_bot}

server:
  port: ${SERVER_PORT:8080}

#  Настройка JWT
jwt:
  secret: ${JWT_SECRET:secretKeyJWTBlablabla1234567890JsonWebTokenSecurityKeyTokenPassword}
  expiration: ${JWT_EXPIRATION:86400000}
